wip: full ts
FriendsOfFlarum/best-answer pull request #107
Opened 2024-10-23 09:58 UTC by imorland

**Fixes #0000**

**Changes proposed in this pull request:**

**Reviewers should focus on:**

**Screenshot**

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).

**Required changes:**

- [ ] Related [Flarum core extension PR's](https://github.com/flarum/core/pulls): (Omit this section if irrelevant)

2024-11-01 16:19 UTC, DavideIadeluca requested changes
Everything appears to be working locally as expected. There are some suggestions I have for typings though, including some changes I picked up that are unrelated to this PR

2024-11-01 16:19 UTC, DavideIadeluca commented on js/src/forum/extenders/extendDiscussionSearchSource.tsx
> +  extend(DiscussionsSearchSource.prototype, 'queryMutators', function (mutators) {
```suggestion
  @ts-ignore
  extend(DiscussionsSearchSource.prototype, 'queryMutators', function (mutators: string[]) {
```

Let's still cast it as `string[]` like it was before so `mutators.push('-is:solved');`  doesn't error and for now add a `@ts-ignore`. Seems like a slight change in core would be needed

2024-11-01 16:19 UTC, DavideIadeluca commented on js/src/forum/extenders/extendDiscussionListState.tsx
> +      (params.filter as Record<string, string>)[`${prepend}solved-discussions`] = 'true';
If we import the `PaginatedListParams` type and use that for the `params` parameter, we can save ourselves this gymnastic and leave it like it was before

```tsx
...
import type { PaginatedListParams } from 'flarum/common/states/PaginatedListState';

export default function extendDiscussionListState() {
  extend(DiscussionListState.prototype, 'requestParams', function (params: PaginatedListParams) {
```

2024-11-01 16:19 UTC, DavideIadeluca commented on js/src/forum/extenders/extendDiscussionComposer.tsx
> +import Tag from 'flarum/tags/common/models/Tag';
```suggestion
import type Tag from 'flarum/tags/common/models/Tag';
```

2024-11-01 16:19 UTC, DavideIadeluca commented on js/src/forum/extend.ts
>  import Post from 'flarum/common/models/Post';
```suggestion
import type Post from 'flarum/common/models/Post';
```

2024-11-01 16:19 UTC, DavideIadeluca commented on js/src/forum/components/SolutionSearchItem.tsx
>  import Discussion from 'flarum/common/models/Discussion';
```suggestion
import type Discussion from 'flarum/common/models/Discussion';
```

2024-11-01 16:19 UTC, DavideIadeluca commented on js/src/forum/components/SolutionSearchItem.tsx
>  import Post from 'flarum/common/models/Post';
```suggestion
import type Post from 'flarum/common/models/Post';
```

2024-11-01 16:19 UTC, DavideIadeluca commented on js/src/forum/components/SolutionSearchItem.tsx
> +import Tag from 'flarum/tags/common/models/Tag';
```suggestion
import type Tag from 'flarum/tags/common/models/Tag';
```

2024-11-01 16:19 UTC, DavideIadeluca commented on js/src/forum/components/SelectBestAnswerNotification.ts
> +import Discussion from 'flarum/common/models/Discussion';
```suggestion
import type Discussion from 'flarum/common/models/Discussion';
```

2024-11-01 21:47 UTC, imorland commented on js/src/@types/shims.d.ts
>  import Post from 'flarum/common/models/Post';
Not sure I follow here??

2024-11-01 21:48 UTC, imorland commented on js/src/forum/components/BestAnswerBadge.tsx
> +    attrs.label = extractText(app.translator.trans('fof-best-answer.forum.answered_badge'));
I totally understand where you're coming from here, but I think this is the way forward, at least for the remaining time on `1.x`. 

Let's alter core for `2.x` as you suggest for the typing...

2024-11-02 06:36 UTC, DavideIadeluca commented on js/src/forum/components/BestAnswerBadge.tsx
> +    attrs.label = extractText(app.translator.trans('fof-best-answer.forum.answered_badge'));
Sounds good to me

2024-11-02 06:41 UTC, DavideIadeluca commented on js/src/@types/shims.d.ts
>  import Post from 'flarum/common/models/Post';
Sorry I could've been more clear. Check out https://github.com/flarum/framework/pull/4097/files#diff-adc7130f3dfa4774617fac483805a1b4206ba70bd0a9f86c073546e1cf36b472R1-R6 for that I mean

2024-11-02 08:09 UTC, DavideIadeluca approved these changes

2024-11-02 08:14 UTC, imorland commented on js/src/@types/shims.d.ts
>  import Post from 'flarum/common/models/Post';
Got it, thanks!

2024-11-02 08:15 UTC, DavideIadeluca approved these changes

2024-11-02 08:19 UTC, merged